theme: jekyll-theme-minimal
title: Path-Seq-Lab INRB-DRC
url: http://inrb-drc.github.io/inrb-website
lang: en

markdown: kramdown
future: true

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from
  - jekyll-twitter-plugin

defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope: 
      path: "fr"
    values:
      lang: "fr"
